### ISSUE TITLE
Invite to contribute in Linguist

### ISSUE THREAD

**Issue by vitonsky** [lawl/translate#1]
Hi, i found you in this thread https://github.com/LibreTranslate/LibreTranslate/issues/55#issuecomment-1118987151

Your prototype is really good, i here, because i research your code and i want to notify you about project https://github.com/translate-tools/linguist

I've create Linguist because i didn't found no one good browser addon for translation. I spend many time on development and i want to people avoid implement same functional few times, so if you want, you are welcome to contribute to Linguist here https://github.com/translate-tools/linguist

I belive that develop one opensource tool together is better than develop few projects with same functional alone. Let's avoid useless work and will contribute to useful features together.

**Comment by lawl** [comment]
thanks i'll take a look
